---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 23.111.78.179/32
      - 23.111.69.218/32
