---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 142.93.110.163/32
      - 147.182.150.60/32
