---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 159.203.61.139/32
      - 134.122.38.203/32
