---
firewalld_add:
  - name: public
    interfaces:
      - ens3
    services:
      - http
      - https
    ports:
      - 22657/tcp
      - 22656/tcp
      - 1317/tcp

  - name: trusted
    sources:
      - 159.203.61.139/32
      - 138.197.165.217/32
