---
firewalld_add:
  - name: public
    interfaces:
      - ens3
    services:
      - http
      - https
    ports:
      - 22657/tcp
      - 22656/tcp
      - 1317/tcp

  - name: trusted
    sources:
      - 147.182.150.60/32
      - 147.182.158.116/32
