---
nginx_packages_intall: false
nginx_server_name_hash: 64
nginx_proxy_read_timeout: 1200
nginx_proxy_send_timeout: 1200
nginx_proxy_connection_timeout: 75

nginx_sites:
  - name: rnt-console
    url: rnt-console.realitynetwork.store
    upstream: http://localhost:8080
    template: basic-proxy
    ssl: true

  - name: rnt-daemon
    url: rnt-daemon.realitynetwork.store
    upstream: http://localhost:9473
    configs:
      - rewrite ^/deployer(/.*)? https://webapp-deployer.pwa.realitynetwork.store permanent
    template: websocket-proxy
    ssl: true
