---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https
    ports:
      - 6443/tcp

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 165.22.238.155/32
      - 68.183.206.252/32
