---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https
    ports:
      - 6443/tcp

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 138.197.165.217/32
      - 134.122.38.203/32
