---
firewalld_add:
  - name: public
    interfaces:
      - enp9s0
    services:
      - http
      - https

  - name: trusted
    sources:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 165.227.34.121/32
      - 167.99.182.224/32
